from produk import RotiManis, Croissant, ButterCookies, Muffin

produk_list = []

def menu(): ...
def tambah_produk(): ...
def tampilkan_produk(): ...
def kalkulator_profit(): ...
def simulasi_produksi(): ...

if __name__ == "__main__":
    menu()
