from abc import ABC, abstractmethod

# Interface
class Baking(ABC): ...
class Packaging(ABC): ...
class Labeling(ABC): ...

# Abstract class
class ProdukRoti(ABC): ...

# Subclasses
class RotiManis(ProdukRoti, Baking, Packaging, Labeling): ...
class Croissant(ProdukRoti, Baking, Packaging, Labeling): ...
class ButterCookies(ProdukRoti, Baking, Packaging, Labeling): ...
class Muffin(ProdukRoti, Baking, Packaging, Labeling): ...
